[versions]
kotlin = "2.4.10"
kotlinter = "5.7.0"
kermit = "2.1.0"
dokka = "2.2.0"
compose-html = "1.11.1"
compose-runtime = "1.11.4"
kobweb = "0.25.0"
vanniktech = "0.37.0"

[libraries]
kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }
compose-html-core = { group = "org.jetbrains.compose.html", name = "html-core", version.ref = "compose-html" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose-runtime" }
kobweb-core = { group = "com.varabyte.kobweb", name = "kobweb-core", version.ref = "kobweb" }
kobweb-silk = { group = "com.varabyte.kobweb", name = "kobweb-silk", version.ref = "kobweb" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kobweb-library = { id = "com.varabyte.kobweb.library", version.ref = "kobweb" }
