name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: iosSimulatorArm64Test
            os: macos-latest
          - target: jvmTest
            os: ubuntu-latest
          - target: jsNodeTest
            os: ubuntu-latest
          - target: testAndroid
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v6
    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@v6
    - uses: actions/cache@v5
      with:
        path: |
          ~/.konan
        key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/actions/setup-gradle@v6
    - name: Run matrix target
      run: ./gradlew ${{ matrix.target }}
