name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@v6
    - name: Set up JDK 25
      uses: actions/setup-java@v5
      with:
        java-version: '25'
        distribution: 'temurin'
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v6
    - name: Run Build
      run: ./gradlew build
